{
 "title": "Load Test Prom Ring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mimir Pod Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\", namespace=\"mimir\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prom Ring Instances Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "up{service=\"prometheus-ring\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  { "title": "Synthetic Metrics (all)", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 } },
  {
   "title": "Number of Targets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "count(synthetic_metric_0{label_0=\"value_0\", label_1=\"value_1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mimir Time Series ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cortex_ingester_tsdb_head_chunks",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Prom Ring Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "prometheus_agent_active_series", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "General Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Machine CPU usage Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=~\"prometheus-ring|node-exporter\",pod!=\"kube-prometheus-stack-prometheus-node-exporter-mtl2q\", mode=~\"system|user\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine Memory Usage Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"prometheus-ring|node-exporter\", pod!=\"kube-prometheus-stack-prometheus-node-exporter-mtl2q\"}\n-\nnode_memory_MemFree_bytes{job=~\"prometheus-ring|node-exporter\", pod!=\"kube-prometheus-stack-prometheus-node-exporter-mtl2q\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "# rate(node_network_receive_bytes_total{}[1m])\nsum(rate(node_network_transmit_bytes_total{pod!=\"kube-prometheus-stack-prometheus-node-exporter-mtl2q\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic Packets/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "# rate(node_network_receive_bytes_total{}[1m])\nsum(rate(node_network_transmit_packets_total{pod!=\"kube-prometheus-stack-prometheus-node-exporter-mtl2q\"}[1m])) by (instance)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Mimir Network Transmited Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{pod!=\"kube-prometheus-stack-prometheus-node-exporter-mtl2q\", service=\"kube-prometheus-stack-prometheus-node-exporter\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prom Ring Network Traffic Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "# rate(node_network_receive_bytes_total{}[1m])\nsum(rate(node_network_transmit_bytes_total{pod!=\"kube-prometheus-stack-prometheus-node-exporter-mtl2q\", job=\"prometheus-ring\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mimir Network Traffic Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{pod!=\"kube-prometheus-stack-prometheus-node-exporter-mtl2q\", job=\"node-exporter\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prom Ring Network Received Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{pod!=\"kube-prometheus-stack-prometheus-node-exporter-mtl2q\", job=\"prometheus-ring\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mimir Network Traffic Packets/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "# rate(node_network_receive_bytes_total{}[1m])\nsum(rate(node_network_transmit_packets_total{pod!=\"kube-prometheus-stack-prometheus-node-exporter-mtl2q\", job=\"node-exporter\"}[1m])) by (instance)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prom Ring Network Traffic Packets/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "# rate(node_network_receive_bytes_total{}[1m])\nsum(rate(node_network_transmit_packets_total{pod!=\"kube-prometheus-stack-prometheus-node-exporter-mtl2q\", job=\"prometheus-ring\"}[1m])) by (instance)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Mimir Machine Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=\"mimir\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prom Ring Machine Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"prometheus-ring\"}\n-\nnode_memory_MemFree_bytes{job=\"prometheus-ring\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mimir Pod Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "# sum(container_memory_usage_bytes{namespace=\"mimir\"}) by (pod)\nmax(container_memory_working_set_bytes{namespace=\"mimir\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Mimir Machine CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"mimir\"}[1m])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prom Ring Machine CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"prometheus-ring\", mode=~\"system|user\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mimir Pod CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"mimir\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU Allocatable",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 311 },
     "targets": [
      {
       "expr": "sum(\n  kube_node_status_allocatable{\n    resource=\"cpu\",\n    node=~\"prom-ring-mimir.*\",\n    node!~\"prom-ring-mimir-controlplane.*\"\n  }\n) by (node)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod Memory usage %limit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 311 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{namespace=\"mimir\"}) by (pod) \n/ max(kube_pod_container_resource_limits{namespace=\"mimir\"}) by (pod) \n* 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mimir Service Availability Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 319 },
     "targets": [
      {
       "expr": "# sum(kube_pod_status_ready{condition=\"true\", namespace=\"mimir\"}) by (pod)\nup{namespace=\"mimir\"}",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Node Memory Allocatable",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 319 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\n  kube_node_status_allocatable{\n    resource=\"memory\",\n    node=~\"prom-ring-mimir.*\",\n    node!~\"prom-ring-mimir-controlplane.*\"\n  }\n) by (node)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}