consul:
  global:
    name: consul
    datacenter: dc1
    enabled: True
    logLevel: debug

  server:
    replicas: 5
    extraConfig: |
      {
        "limits": {
          "http_max_conns_per_client": 100000
        }
      }
    exposeService:
      enabled: true
      type: LoadBalancer
    resources:
      requests:
        memory: "200Mi"
        cpu: "100m"
      limits:
        memory: "2Gi"
        cpu: "1"
