---

- name: Ensure necessary packages are installed
  apt:
    name: curl
    state: present
  when: ansible_os_family == "Debian"

- name: Create node_exporter user
  user:
    name: node_exporter
    shell: /usr/sbin/nologin

- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'

- name: Extract Node Exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move binary to /usr/local/bin
  copy:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0755'
    remote_src: yes

- name: Create systemd service file
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      ExecStart=/usr/local/bin/node_exporter
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start Node Exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: started

- name: Cleanup temporary files
  file:
    path: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64
    state: absent

- name: Remove downloaded archive
  file:
    path: /tmp/node_exporter.tar.gz
    state: absent
