apiVersion: v1
kind: Pod
metadata:
  name: netshoot-pod
  labels:
    app: netshoot
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep", "3600"]
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "mimir"
    effect: "NoSchedule"
