# Disabled once there will be no alerts
alertmanager:
  enabled: false

prometheus:
  enabled: true

  prometheusSpec: # Tolerations for Prometheus StatefulSet are often under prometheusSpec
    tolerations: &metamonitoringToleration
    - key: "role"
      operator: "Equal"
      value: "metamonitoring"
      effect: "NoSchedule"
    storageSpec:
     volumeClaimTemplate:
       spec:
         storageClassName: "cinder-storageclass"
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 50Gi

grafana:
  enabled: true
  adminPassword: admin
  service:
    type: LoadBalancer
  tolerations: *metamonitoringToleration
  additionalDataSources:
  - name: Mimir
    type: prometheus
    url: http://mimir-nginx.mimir.svc:80/prometheus
    access: proxy
    isDefault: false
  persistence:
    enabled: true
    type: sts
    storageClassName: "cinder-storageclass"
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection

kubeStateMetrics:
  enabled: true
  tolerations: *metamonitoringToleration

nodeExporter:
  enabled: true
  tolerations: *metamonitoringToleration


prometheusOperator:
  enabled: true
  # Add tolerations for the admission webhook jobs as well
  admissionWebhooks:
    enabled: true
    deployment:
      tolerations: *metamonitoringToleration
    patch:
      tolerations: *metamonitoringToleration
  tolerations: *metamonitoringToleration