# VMs
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: prometheus-ring-machines
  namespace: kube-prometheus
  labels:
    prometheus: system-monitoring-prometheus
    job: prometheus-ring
    release: kube-prometheus-stack
spec:
  staticConfigs:
    - labels:
        job: prometheus-ring
      targets:
          # Virtual Machines
        - 177.93.133.85:9100
        - 177.93.133.114:9100
        - 177.93.133.115:9100
---
# Prometheus Ring
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: prometheus-ring-instances
  namespace: kube-prometheus
  labels:
    prometheus: system-monitoring-prometheus
    job: prometheus-ring-instances
    release: kube-prometheus-stack
spec:
  staticConfigs:
    - labels:
        job: prometheus-ring
        service: prometheus-ring
      targets:
        # Prometheus Ring Nodes
        - 177.93.133.115:19090
        - 177.93.133.115:19091
        - 177.93.133.115:19092
        - 177.93.133.115:19093
        - 177.93.133.115:19094
        - 177.93.133.115:19095
        - 177.93.133.115:19096
        - 177.93.133.115:19097
        - 177.93.133.115:19098
        - 177.93.133.115:19099
        - 177.93.133.115:19100